import 'package:projekt_481_play_with_me/feature/info_players/models/player_item.dart';

List<PlayerProfil> players = [
  PlayerProfil(
    firstName: "Michael",
    lastName: "Jordan",
    nickName: "MJ",
    avatarUrl: "",
    availavility: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  PlayerProfil(
    firstName: "Mike",
    lastName: "Viking",
    nickName: "MV",
    avatarUrl: "",
    availavility: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  PlayerProfil(
    firstName: "Shaquille",
    lastName: "O'Neal",
    nickName: "Shaq",
    avatarUrl: "",
    availavility: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  PlayerProfil(
    firstName: "Dražen ",
    lastName: "Petrović",
    nickName: "Basketball-Mozart",
    avatarUrl: "",
    availavility: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  PlayerProfil(
    firstName: "Stephen",
    lastName: "Curry",
    nickName: "Chef Curry",
    avatarUrl: "",
    availavility: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  PlayerProfil(
    firstName: "Toni",
    lastName: "Kukoč ",
    nickName: "Die kroatische Sensation",
    avatarUrl: "",
    availavility: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  PlayerProfil(
    firstName: "Dino",
    lastName: "Rađa",
    nickName: "König von Split",
    avatarUrl: "",
    availavility: ['Vielleicht'],
    sendMessage: false,
    online: true,
  ),
  PlayerProfil(
    firstName: "Kevin",
    lastName: "Durant",
    nickName: "KD",
    avatarUrl: "",
    availavility: ['Vielleicht'],
    sendMessage: false,
    online: true,
  ),
  PlayerProfil(
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    nickName: "Greek Freak",
    avatarUrl: "assets/images/antetokounmpo.png",
    availavility: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  PlayerProfil(
    firstName: "James",
    lastName: "Harden",
    nickName: "The Beard",
    avatarUrl: "",
    availavility: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  PlayerProfil(
    firstName: "Dirk",
    lastName: "Nowitzki",
    nickName: "Wunderkind",
    avatarUrl: "",
    availavility: ['Nein'],
    sendMessage: false,
    online: true,
  ),
  PlayerProfil(
    firstName: "Tim",
    lastName: "Duncan",
    nickName: "The Big Fundamental",
    avatarUrl: "",
    availavility: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  PlayerProfil(
    firstName: "Magic",
    lastName: "Johnson",
    nickName: "Magic",
    avatarUrl: "",
    availavility: ['Ja'],
    sendMessage: false,
    online: true,
  ),
];
