import 'package:projekt_481_play_with_me/feature/info_players/models/player.dart';

List<Player> players = [
  Player(
    userId: "",
    firstName: "Michael",
    lastName: "Jordan",
    nickName: "MJ",
    userName: "MiJ",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Mike",
    lastName: "Viking",
    nickName: "MV",
    userName: "MiV",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Shaquille",
    lastName: "O'Neal",
    nickName: "Shaq",
    userName: "ShQ",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Dražen ",
    lastName: "Petrović",
    nickName: "Basketball-Mozart",
    userName: "BsM",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Stephen",
    lastName: "Curry",
    nickName: "Chef Curry",
    userName: "ChC",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Toni",
    lastName: "Kukoč ",
    nickName: "Die kroatische Sensation",
    userName: "DkS",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Dino",
    lastName: "Rađa",
    nickName: "König von Split",
    userName: "KvS",
    eMail: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Kevin",
    lastName: "Durant",
    nickName: "KD",
    userName: "KeD",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    nickName: "Greek Freak",
    userName: "GrF",
    eMail: "",
    avatarUrl: "assets/images/antetokounmpo.png",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "James",
    lastName: "Harden",
    nickName: "The Beard",
    userName: "ThB",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Dirk",
    lastName: "Nowitzki",
    nickName: "Wunderkind",
    userName: "WuD",
    eMail: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Tim",
    lastName: "Duncan",
    nickName: "The Big Fundamental",
    userName: "TbF",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Magic",
    lastName: "Johnson",
    nickName: "Magic",
    userName: "MaG",
    eMail: "",
    password: "",
    avatarUrl: "",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
];
