// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUsrUc43DZzB3WxhvmgB_y7_vK521JaQE',
    appId: '1:600520037224:web:cb9e00a525263e19d3bcdd',
    messagingSenderId: '600520037224',
    projectId: 'playwithme-8770d',
    authDomain: 'playwithme-8770d.firebaseapp.com',
    storageBucket: 'playwithme-8770d.firebasestorage.app',
    measurementId: 'G-X2JHRN2GM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGeRjPL7ovF2_vXXnxrEL2DCgm9l-sWs',
    appId: '1:600520037224:android:e748699966d52414d3bcdd',
    messagingSenderId: '600520037224',
    projectId: 'playwithme-8770d',
    storageBucket: 'playwithme-8770d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmp2oFP5xuP6U2D6smC7IRbmSy-BMd-Kc',
    appId: '1:600520037224:ios:c5a9d2d7e2ed008bd3bcdd',
    messagingSenderId: '600520037224',
    projectId: 'playwithme-8770d',
    storageBucket: 'playwithme-8770d.firebasestorage.app',
    iosBundleId: 'com.example.projekt481PlayWithMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmp2oFP5xuP6U2D6smC7IRbmSy-BMd-Kc',
    appId: '1:600520037224:ios:c5a9d2d7e2ed008bd3bcdd',
    messagingSenderId: '600520037224',
    projectId: 'playwithme-8770d',
    storageBucket: 'playwithme-8770d.firebasestorage.app',
    iosBundleId: 'com.example.projekt481PlayWithMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUsrUc43DZzB3WxhvmgB_y7_vK521JaQE',
    appId: '1:600520037224:web:b5f4b559ddc69213d3bcdd',
    messagingSenderId: '600520037224',
    projectId: 'playwithme-8770d',
    authDomain: 'playwithme-8770d.firebaseapp.com',
    storageBucket: 'playwithme-8770d.firebasestorage.app',
    measurementId: 'G-Z8CGYZN323',
  );

}